platform :ios, '7.0'

inhibit_all_warnings!

link_with 'Testing'

# Add Application pods here

pod 'AFNetworking', '~> 2.5.3'
pod 'AFNetworking-RACExtensions'
pod 'DOSingleton'
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'